/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerPlaylist;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
/**
 *
 * @author rodri
 */
public class PlaylistFrame extends javax.swing.JFrame {

    private ControllerPlaylist c; 

    public PlaylistFrame() {
        initComponents();
        c = new ControllerPlaylist(this);
    }

    public JButton getBt_adicionar_musica() {
        return bt_adicionar_musica;
    }

    public void setBt_adicionar_musica(JButton bt_adicionar_musica) {
        this.bt_adicionar_musica = bt_adicionar_musica;
    }

    public JButton getBt_view_playlist() {
        return bt_view_playlist;
    }

    public void setBt_view_playlist(JButton bt_view_playlist) {
        this.bt_view_playlist = bt_view_playlist;
    }

    public JButton getBt_criar_playlist() {
        return bt_criar_playlist;
    }

    public void setBt_criar_playlist(JButton bt_criar_playlist) {
        this.bt_criar_playlist = bt_criar_playlist;
    }

    public JButton getBt_remover_musica() {
        return bt_remover_musica;
    }

    public void setBt_remover_musica(JButton bt_remover_musica) {
        this.bt_remover_musica = bt_remover_musica;
    }

    public JButton getBt_excluir_playlist() {
        return bt_excluir_playlist;
    }

    public void setBt_excluir_playlist(JButton bt_excluir_playlist) {
        this.bt_excluir_playlist = bt_excluir_playlist;
    }

    public JLabel getLbl_playlist_edit() {
        return lbl_playlist_edit;
    }

    public void setLbl_playlist_edit(JLabel lbl_playlist_edit) {
        this.lbl_playlist_edit = lbl_playlist_edit;
    }

    public JLabel getLbl_playlist_buscar() {
        return lbl_playlist_buscar;
    }

    public void setLbl_playlist_buscar(JLabel lbl_playlist_buscar) {
        this.lbl_playlist_buscar = lbl_playlist_buscar;
    }

    public JLabel getLbl_playlist_buscar_titulo() {
        return lbl_playlist_buscar_titulo;
    }

    public void setLbl_playlist_buscar_titulo(JLabel lbl_playlist_buscar_titulo) {
        this.lbl_playlist_buscar_titulo = lbl_playlist_buscar_titulo;
    }

    public JTextField getTxt_playlist() {
        return txt_playlist;
    }

    public void setTxt_playlist(JTextField txt_playlist) {
        this.txt_playlist = txt_playlist;
    }

    public JTextField getTxt_titulo_add_remove() {
        return txt_titulo_add_remove;
    }

    public void setTxt_titulo_add_remove(JTextField txt_titulo_add_remove) {
        this.txt_titulo_add_remove = txt_titulo_add_remove;
    }

    public JTextField getTxt_playlist_add_remove() {
        return txt_playlist_add_remove;
    }

    public void setTxt_playlist_add_remove(JTextField txt_playlist_add_remove) {
        this.txt_playlist_add_remove = txt_playlist_add_remove;
    }

    public JList<String> getList_musicas_playlist() {
        return list_musicas_playlist;
    }

    public void setList_playlist1(JList<String> list_playlist1) {
        this.list_playlist = list_playlist1;
    }

    public JList<String> getList_playlist1() {
        return list_playlist;
    }

    public void setList_musicas_playlist(JList<String> list_musicas_playlist) {
        this.list_musicas_playlist = list_musicas_playlist;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_excluir_playlist = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_playlist = new javax.swing.JList<>();
        bt_criar_playlist = new javax.swing.JButton();
        txt_playlist = new javax.swing.JTextField();
        lbl_playlist_edit = new javax.swing.JLabel();
        txt_playlist_add_remove = new javax.swing.JTextField();
        bt_adicionar_musica = new javax.swing.JButton();
        bt_remover_musica = new javax.swing.JButton();
        lbl_playlist_buscar = new javax.swing.JLabel();
        txt_titulo_add_remove = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_musicas_playlist = new javax.swing.JList<>();
        bt_view_playlist = new javax.swing.JButton();
        lbl_playlist_buscar_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_excluir_playlist.setText("Excluir");
        bt_excluir_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_playlistActionPerformed(evt);
            }
        });

        list_playlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list_playlist);

        bt_criar_playlist.setText("Criar");
        bt_criar_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_criar_playlistActionPerformed(evt);
            }
        });

        lbl_playlist_edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_playlist_edit.setText("Playlist:");

        bt_adicionar_musica.setText("Adicionar");
        bt_adicionar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionar_musicaActionPerformed(evt);
            }
        });

        bt_remover_musica.setText("Remover");
        bt_remover_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_remover_musicaActionPerformed(evt);
            }
        });

        lbl_playlist_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_playlist_buscar.setText("Playlist:");

        list_musicas_playlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_musicas_playlist);

        bt_view_playlist.setText("View");
        bt_view_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_view_playlistActionPerformed(evt);
            }
        });

        lbl_playlist_buscar_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_playlist_buscar_titulo.setText("Titulo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(bt_criar_playlist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluir_playlist))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_playlist_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bt_adicionar_musica)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_view_playlist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_remover_musica, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_titulo_add_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_playlist_buscar_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_playlist_buscar))
                        .addGap(18, 18, 18)
                        .addComponent(txt_playlist_add_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_playlist_edit))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_criar_playlist)
                            .addComponent(bt_excluir_playlist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_playlist_buscar)
                            .addComponent(txt_playlist_add_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_playlist_buscar_titulo)
                            .addComponent(txt_titulo_add_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_adicionar_musica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_remover_musica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_view_playlist))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_criar_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criar_playlistActionPerformed
        c.criarPlaylist();
    }//GEN-LAST:event_bt_criar_playlistActionPerformed

    private void bt_excluir_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_playlistActionPerformed
        c.excluirPlaylist();
    }//GEN-LAST:event_bt_excluir_playlistActionPerformed

    private void bt_adicionar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionar_musicaActionPerformed
        c.adicionarMusica();
    }//GEN-LAST:event_bt_adicionar_musicaActionPerformed

    private void bt_remover_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_remover_musicaActionPerformed
        c.removerMusica();
    }//GEN-LAST:event_bt_remover_musicaActionPerformed

    private void bt_view_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_view_playlistActionPerformed
        c.mostrarMusicasPlaylist();
    }//GEN-LAST:event_bt_view_playlistActionPerformed

            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar_musica;
    private javax.swing.JButton bt_criar_playlist;
    private javax.swing.JButton bt_excluir_playlist;
    private javax.swing.JButton bt_remover_musica;
    private javax.swing.JButton bt_view_playlist;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_playlist_buscar;
    private javax.swing.JLabel lbl_playlist_buscar_titulo;
    private javax.swing.JLabel lbl_playlist_edit;
    private javax.swing.JList<String> list_musicas_playlist;
    private javax.swing.JList<String> list_playlist;
    private javax.swing.JTextField txt_playlist;
    private javax.swing.JTextField txt_playlist_add_remove;
    private javax.swing.JTextField txt_titulo_add_remove;
    // End of variables declaration//GEN-END:variables
}
