/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerSpotifei;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import view.SpotifeiFrame;
import view.HistoricoFrame;
import view.PlaylistFrame;


/**
 *
 * @author unifrcastanho
 */
public class SpotifeiFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpotifeiFrame
     */
    public SpotifeiFrame() {
        initComponents();
        c = new ControllerSpotifei(this);
    }

    public JButton getBt_buscar_musica() {
        return bt_buscar_musica;
    }

    public void setBt_buscar_musica(JButton bt_buscar_musica) {
        this.bt_buscar_musica = bt_buscar_musica;
    }

    public JButton getBt_curtir_playlist() {
        return bt_curtir_playlist;
    }

    public void setBt_curtir_playlist(JButton bt_curtir_playlist) {
        this.bt_curtir_playlist = bt_curtir_playlist;
    }

    public JButton getBt_descurtir_playlist() {
        return bt_descurtir_playlist;
    }

    public void setBt_descurtir_playlist(JButton bt_descurtir_playlist) {
        this.bt_descurtir_playlist = bt_descurtir_playlist;
    }

    public JButton getBt_historico() {
        return bt_historico;
    }

    public void setBt_historico(JButton bt_historico) {
        this.bt_historico = bt_historico;
    }

    public JButton getBt_playlist() {
        return bt_playlist;
    }

    public void setBt_playlist(JButton bt_playlist) {
        this.bt_playlist = bt_playlist;
    }

    public JLabel getLbl_artista_buscar() {
        return lbl_artista_buscar;
    }

    public void setLbl_artista_buscar(JLabel lbl_artista_buscar) {
        this.lbl_artista_buscar = lbl_artista_buscar;
    }

    public JLabel getLbl_genero_buscar() {
        return lbl_genero_buscar;
    }

    public void setLbl_genero_buscar(JLabel lbl_genero_buscar) {
        this.lbl_genero_buscar = lbl_genero_buscar;
    }

    public JLabel getLbl_titulo_buscar() {
        return lbl_titulo_buscar;
    }

    public void setLbl_titulo_buscar(JLabel lbl_titulo_buscar) {
        this.lbl_titulo_buscar = lbl_titulo_buscar;
    }

    public JTextField getTxt_artista_buscar() {
        return txt_artista_buscar;
    }

    public void setTxt_artista_buscar(JTextField txt_artista_buscar) {
        this.txt_artista_buscar = txt_artista_buscar;
    }

    public void setTxt_genero_buscar(JTextField txt_genero_buscar) {
        this.txt_genero_buscar = txt_genero_buscar;
    }

    public JTextField getTxt_titulo_buscar() {
        return txt_titulo_buscar;
    }

    public void setTxt_titulo_buscar(JTextField txt_titulo_buscar) {
        this.txt_titulo_buscar = txt_titulo_buscar;
    }
    
    public JTextField getTxt_genero_buscar() {
        return txt_genero_buscar;
    }

    public JTable getTable_buscar_musicas() {
        return table_buscar_musicas;
    }

    public void setTable_buscar_musicas(JTable table_buscar_musicas) {
        this.table_buscar_musicas = table_buscar_musicas;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_titulo_buscar = new javax.swing.JTextField();
        lbl_genero_buscar = new javax.swing.JLabel();
        lbl_artista_buscar = new javax.swing.JLabel();
        txt_artista_buscar = new javax.swing.JTextField();
        txt_genero_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_buscar_musicas = new javax.swing.JTable();
        bt_curtir_playlist = new javax.swing.JButton();
        bt_descurtir_playlist = new javax.swing.JButton();
        bt_buscar_musica = new javax.swing.JButton();
        lbl_titulo_buscar = new javax.swing.JLabel();
        bt_playlist = new javax.swing.JButton();
        bt_historico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_genero_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_genero_buscar.setText("Genero:");

        lbl_artista_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_artista_buscar.setText("Artista:");

        table_buscar_musicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_buscar_musicas);

        bt_curtir_playlist.setText("Curtir");
        bt_curtir_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtir_playlistActionPerformed(evt);
            }
        });

        bt_descurtir_playlist.setText("Descurtir");
        bt_descurtir_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descurtir_playlistActionPerformed(evt);
            }
        });

        bt_buscar_musica.setText("Buscar");
        bt_buscar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscar_musicaActionPerformed(evt);
            }
        });

        lbl_titulo_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_titulo_buscar.setText("Titulo:");

        bt_playlist.setText("Playlist");
        bt_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_playlistActionPerformed(evt);
            }
        });

        bt_historico.setText("Historico");
        bt_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_genero_buscar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_titulo_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_artista_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_artista_buscar)
                                            .addComponent(txt_genero_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_historico))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_titulo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_playlist))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_curtir_playlist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_descurtir_playlist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_buscar_musica)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo_buscar)
                    .addComponent(bt_playlist))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_artista_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_historico)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbl_artista_buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_genero_buscar)
                    .addComponent(txt_genero_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_curtir_playlist)
                    .addComponent(bt_descurtir_playlist)
                    .addComponent(bt_buscar_musica))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_curtir_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtir_playlistActionPerformed
        c.curtirMusica();
    }//GEN-LAST:event_bt_curtir_playlistActionPerformed

    private void bt_descurtir_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descurtir_playlistActionPerformed
        c.descurtirMusica();
    }//GEN-LAST:event_bt_descurtir_playlistActionPerformed

    private void bt_buscar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscar_musicaActionPerformed
        // TODO add your handling code here:
        c.buscarMusicas();
    }//GEN-LAST:event_bt_buscar_musicaActionPerformed

    private void bt_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_historicoActionPerformed
        c.abrirHistorico();
    }//GEN-LAST:event_bt_historicoActionPerformed

    private void bt_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_playlistActionPerformed
        c.abrirPlaylists();
    }//GEN-LAST:event_bt_playlistActionPerformed

    

    private ControllerSpotifei c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar_musica;
    private javax.swing.JButton bt_curtir_playlist;
    private javax.swing.JButton bt_descurtir_playlist;
    private javax.swing.JButton bt_historico;
    private javax.swing.JButton bt_playlist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_artista_buscar;
    private javax.swing.JLabel lbl_genero_buscar;
    private javax.swing.JLabel lbl_titulo_buscar;
    private javax.swing.JTable table_buscar_musicas;
    private javax.swing.JTextField txt_artista_buscar;
    private javax.swing.JTextField txt_genero_buscar;
    private javax.swing.JTextField txt_titulo_buscar;
    // End of variables declaration//GEN-END:variables
}
